/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartBaseV3: typeof import('./src/components/global/chart-base-v3.vue')['default']
    ComsTitle: typeof import('./src/components/global/coms-title.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    GlobalSelect: typeof import('./src/components/global/global-select.vue')['default']
    GlobalSvg: typeof import('./src/components/global/global-svg.vue')['default']
    Loading: typeof import('./src/components/global/loading.vue')['default']
    OverviewsLayout: typeof import('./src/components/global/overviews-layout.vue')['default']
    OverviewsTable: typeof import('./src/components/global/overviews-table.vue')['default']
    PinyinConversion: typeof import('./src/components/global/pinyin-conversion.vue')['default']
    QinganEc: typeof import('./src/components/global/qingan-ec.vue')['default']
    RelationalEc: typeof import('./src/components/global/relational-ec.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SentenceAnalysisEc: typeof import('./src/components/global/sentence-analysis-ec.vue')['default']
    TreeRelationalEc: typeof import('./src/components/global/tree-relational-ec.vue')['default']
    Upload: typeof import('./src/components/global/upload.vue')['default']
    WordAddColor: typeof import('./src/components/global/word-add-color.vue')['default']
    WordCloudEc: typeof import('./src/components/global/word-cloud-ec.vue')['default']
  }
}
